server:
  port: 8099
  servlet:
    context-path: /sell
spring:
  jpa:
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf8&useSSL=false&useUnicode=true
    username: root
    password: 123456
  devtools:
    restart:
      enabled: true
  jackson:
    default-property-inclusion: non_null
  freemarker:
    charset: utf-8
    suffix: .ftl
    cache: false
  redis:
    host: localhost


wechat:

  #  微信公众平台测试号
  mpAppId: wx6a27fb0ea2ba7ce5
  mpAppSecret: a93a35a57fb92d85097ba327f08ed899

  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e

  #支付时用到的公众平台AppId
  mpPayAppId: wxd898fcb01713c658
  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  keyPath: /var/wechat-pay/h5.p12
  notifyUrl: http://4appsell.natapp1.cc/sell/pay/notify
  #支付时用到的openId
  payOpenId: oTgZpwX4spaRFEKBvZgMc1IrqUzg



project-url:
  sell: http://4appsell.natapp1.cc/sell
  weChatMpAuthorize: http://4appsell.natapp1.cc/sell
  weChatOpenAuthorize: http://4appsell.natapp1.cc/sell


#logging:
#  pattern:
#    console: "%d - %msg%n"
#  path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log